spring:
  application:
    name: system-b
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:file:./Database
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  jpa:
    hibernate:
      ddl-auto: update


server:
  port: 8081